version: "3"
services:
  app:
    image: go-app
    depends_on:
      - redis
    networks:
      - webnet
    environment:
      REDIS_URL: redis:6379

  node:
    image: node-web
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - webnet
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:alpine
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
