version: "3"
services:
  app:
    image: golang:1.6.1-alpine
    volumes:
      - .:/go/src/go-with-compose
    command: go run consume.go
    links:
      - redis

  node:
    image: testnode
    ports:
      - "3000:3000"
    networks:
      - webnet
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:alpine
    networks:
      - webnet

networks:
  webnet:
