version: "3"
services:
  app:
    image: golang:1.6.1-alpine
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/data-process"
    command: go run url_working.go
    depends_on:
      - redis
    networks:
      - webnet
    environment:
      REDIS_URL: redis:6379

  node:
    image: testnode
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - webnet
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:alpine
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
